spring:
  datasource:
    url: jdbc:postgresql://ANTB-279:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://ANTB-279:8080/realms/SpringBootKeycloak
      client:
        registration:
          keycloak:
            client-id: login-user-app
            authorization-grant-type: authorization_code
            scope: openid 
        provider:
          keycloak:
            issuer-uri: http://ANTB-279:8080/realms/SpringBootKeycloak
            use-resource-role-mappings: false
        user-name-attribute: preferred_username     
liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.yaml
server:
  port: 8081

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG  
      springframework: info
        jdbc:
          core: DEBUG  
    liquibase: debug
    
